push_indications:
  name: Передать показания
  description: 'Передать показания в личный кабинет'
  target:
    entity:
      integration: guk_krasnodar
      device_class: guk_krasnodar_meter
  fields:
    indications:
      name: Значение показаний
      description: 'Значение показаний БЕЗ десятичной части (до точки)'
      required: true
      advanced: false
      example: '123'
      selector:
        text:
          multiline: false
    notification:
      name: Показывать уведомление
      description: 'Показывать уведомление при успешной передаче'
      required: false
      advanced: false
      default: false
      example: 'true'
      selector:
        boolean:
    ignore_indications:
      name: Игнорировать ограничения
      description: 'Игнорировать ограничения по показаниям'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:
