push_indications:
  description: 'Передать показания в личный кабинет'
  target:
    entity:
      integration: guk_krasnodar
      device_class: guk_krasnodar_meter
  fields:
    indications:
      description: 'Значение показаний БЕЗ десятичной части (до точки)'
      required: true
      advanced: false
      example: '123'
      selector:
        text:
          multiline: false
    notification:
      description: 'Показывать уведомление при успешной передаче'
      required: false
      advanced: false
      default: false
      example: 'true'
      selector:
        boolean:
    ignore_indications:
      description: 'Игнорировать ограничения по показаниям'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:
