push_indications:
  name: 'Передача показаний'
  description: 'Передать показания счётчика воды в личный кабинет'
  target:
    entity:
      integration: guk_krasnodar
      device_class: guk_krasnodar_meter
  fields:
    indications:
      name: 'Значение показаний'
      description: 'Значение показаний БЕЗ десятичной части (до точки).'
      required: true
      advanced: false
      example: '123'
      selector:
        text:
          multiline: false
    indication_entity:
      name: 'Объект (метрика) для показаний'
      description: 'Объект, из которого будет взято значение для отправки. Применяется если в значении показаний указан 0.'
      required: false
      advanced: false
      selector:
        entity:
          multiple: false
          filter:
            - device_class: water
