push_indications:
  name: 'Push indications'
  description: 'Передать показания в личный кабинет'
  target:
    entity:
      integration: guk_krasnodar
      device_class: guk_krasnodar_meter
  fields:
    indications:
      name: 'Indications'
      description: 'Значение показаний БЕЗ десятичной части (до точки). 0 - использовать значение из объекта ниже'
      required: true
      advanced: false
      example: '123'
      selector:
        text:
          multiline: false
    notification:
      name: 'Notification'
      description: 'Показывать уведомление при успешной передаче'
      required: false
      advanced: false
      default: false
      example: 'true'
      selector:
        boolean:
    indication_entity:
      name: 'Indication Entity'
      description: 'Объект, из которого будет взято значение для отправки'
      required: false
      advanced: false
      selector:
        entity:
          multiple: false
          filter:
            - device_class: water
